import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: "category",
      label: "Docs",
      items: [
        "intro",
        {
          type: "category",
          label: "Schema",
          link: {
            type: "generated-index",
            description:
              "DynamoDB, despite being a NoSQL database, is not devoid of schema. In fact, it maintains a flexible schema model. DynamoQL, aligning with this characteristic, is built upon the idea of Schemas and is fully compatible with DynamoDB. While DynamoDB allows for dynamic and evolving data structures, DynamoQL leverages the concept of Schema to provide developers with a structured and organized approach to working with DynamoDB. This compatibility ensures that developers using DynamoQL can seamlessly navigate and interact with the rich features of DynamoDB, all within the context of a well-defined schema.",
          },
          items: ["schema/Define a Schema", { type: "category", label: "Data Types", items: [{ type: "autogenerated", dirName: "schema/data-types" }] }, { type: "category", label: "Type Utilities", link: { type: "generated-index", description: "Schema class provides various type definitions which we can use in TypeScript and JSDoc. They can only be used as types and not as JS value." }, items: [{ type: "autogenerated", dirName: "schema/type-utilities" }] }, "schema/Advanced"],
        },
        {
          type: "category",
          label: "Model",
          link: { type: "generated-index", description: "DynamoQL Model creates a bridge between a Schema and DynamoDB table with a high level API." },
          items: ["model/Define a Model", { type: "category", label: "API", items: [{ type: "autogenerated", dirName: "model/API" }] }, "model/Extend Model"],
        },
        "Error Handling",
        "FAQ",
      ],
    },
  ],
};

export default sidebars;
